config_1:
  config_name: "supervised_GAN_config1"
  S_0: 1
  mu: 0.05
  sigma: 0.2
  n_steps: 100
  n_paths: 1000
  dt: 0.05
  number_data_points: 100000
  epochs: 200
  batch_size: 1000
  advancing_C: 2
  log_freq: 10
  use_Z: true

config_2:
  config_name: "condition_GAN_config2"
  S_0: 1
  mu: 0.05
  sigma: 0.2
  n_steps: 100
  n_paths: 1000
  dt: 0.05
  number_data_points: 100000
  epochs: 200
  batch_size: 1000
  advancing_C: 2
  log_freq: 10
  use_Z: false

config_3:
  config_name: "small_supervised_GAN_config3"
  S_0: 1
  mu: 0.05
  sigma: 0.2
  n_steps: 50
  n_paths: 5
  dt: 0.05
  number_data_points: 15
  epochs: 2
  batch_size: 5
  advancing_C: 2
  log_freq: 10
  use_Z: true