config_1:
  config_name: "cGAN_GBM"
  process : 'GBM'
  S_0: 1
  mu: 0.05
  sigma: 0.2
  dts: [0.05, 0.1, 0.2, 0.4, 0.5, 0.67, 1, 2]
  T: 2
  use_Z: false
  number_data_points: 100000
  epochs: 200
  batch_size: 1000
  advancing_C: 2
  log_freq: 10

config_2:
  config_name: "scGAN_GBM"
  process : 'GBM'
  S_0: 1
  mu: 0.05
  sigma: 0.2
  dts: [0.05, 0.1, 0.2, 0.4, 0.5, 0.67, 1, 2]
  T: 2
  use_Z: true
  number_data_points: 100000
  epochs: 200
  batch_size: 1000
  advancing_C: 2
  log_freq: 10

config_3:
  config_name: "cGAN_CIR_Feller"
  process : 'CIR'
  S_0: 0.1
  S_bar: 0.1
  kappa: 0.1
  gamma: 0.1
  dts: [0.05, 0.1, 0.2, 0.4, 0.5, 0.67, 1, 2]
  T: 2
  use_Z: false
  number_data_points: 100000
  epochs: 200
  batch_size: 1000
  advancing_C: 2
  log_freq: 10

config_4:
  config_name: "cGAN_CIR_no_Feller"
  process : 'CIR'
  S_0: 0.1
  S_bar: 0.1
  kappa: 0.1
  gamma: 0.3
  dts: [0.05, 0.1, 0.2, 0.4, 0.5, 0.67, 1, 2]
  T: 2
  use_Z: false
  number_data_points: 100000
  epochs: 200
  batch_size: 1000
  advancing_C: 2
  log_freq: 10

config_5:
  config_name: "scGAN_CIR_Feller"
  process : 'CIR'
  S_0: 0.1
  S_bar: 0.1
  kappa: 0.1
  gamma: 0.1
  dts: [0.05, 0.1, 0.2, 0.4, 0.5, 0.67, 1, 2]
  T: 2
  use_Z: true
  number_data_points: 100000
  epochs: 200
  batch_size: 1000
  advancing_C: 2
  log_freq: 10

config_6:
  config_name: "scGAN_CIR_no_Feller"
  process : 'CIR'
  S_0: 0.1
  S_bar: 0.1
  kappa: 0.1
  gamma: 0.3
  dts: [0.05, 0.1, 0.2, 0.4, 0.5, 0.67, 1, 2]
  T: 2
  use_Z: true
  number_data_points: 100000
  epochs: 200
  batch_size: 1000
  advancing_C: 2
  log_freq: 10
