config_1:
  config_name: "supervised_GAN_GBM_config1"
  process : 'GBM'
  S_0: 1
  mu: 0.05
  sigma: 0.2
  n_steps: 100
  n_paths: 1000
  dt: 0.05
  number_data_points: 100000
  epochs: 200
  batch_size: 1000
  advancing_C: 2
  log_freq: 10
  use_Z: true

config_2:
  config_name: "condition_GAN_GBM_config2"
  process : 'GBM'
  S_0: 1
  mu: 0.05
  sigma: 0.2
  n_steps: 100
  n_paths: 1000
  dt: 0.05
  number_data_points: 100000
  epochs: 200
  batch_size: 1000
  advancing_C: 2
  log_freq: 10
  use_Z: false

config_3:
  config_name: "small_supervised_GAN_GBM_config3"
  process : 'GBM'
  S_0: 1
  mu: 0.05
  sigma: 0.2
  n_steps: 50
  n_paths: 5
  dt: 0.05
  number_data_points: 15
  epochs: 2
  batch_size: 5
  advancing_C: 2
  log_freq: 10
  use_Z: true

config_4:
  config_name: "condition_GAN_CIR_config4"
  process : 'CIR'
  S_0: 0.1
  kappa: 0.1
  S_bar: 0.1
  gamma : 0.1
  n_steps: 100
  n_paths: 1000
  dt: 0.05
  number_data_points: 100000
  epochs: 200
  batch_size: 1000
  advancing_C: 2
  log_freq: 10
  use_Z: false

config_5:
  config_name: "supervised_GAN_CIR_config5"
  process : 'CIR'
  S_0: 0.1
  kappa: 0.1
  S_bar: 0.1
  gamma : 0.1
  n_steps: 100
  n_paths: 1000
  dt: 0.05
  number_data_points: 100000
  epochs: 200
  batch_size: 1000
  advancing_C: 2
  log_freq: 10
  use_Z: true