config_1:
  config_name: "cGAN_GBM_single_dt"
  process : 'GBM'
  S_0: 1
  mu: 0.05
  sigma: 0.2
  n_steps: 100
  n_paths: 1000
  dt: 0.05
  number_data_points: 100000
  epochs: 200
  batch_size: 1000
  advancing_C: 2
  log_freq: 10
  use_Z: false

config_2:
  config_name: "scGAN_GBM_single_dt"
  process : 'GBM'
  S_0: 1
  mu: 0.05
  sigma: 0.2
  n_steps: 100
  n_paths: 1000
  dt: 0.05
  number_data_points: 100000
  epochs: 200
  batch_size: 1000
  advancing_C: 2
  log_freq: 10
  use_Z: true

config_3:
  config_name: "cGAN_CIR_single_dt"
  process : 'CIR'
  S_0: 0.1
  kappa: 0.1
  S_bar: 0.1
  gamma : 0.1
  n_steps: 100
  n_paths: 1000
  dt: 0.05
  number_data_points: 100000
  epochs: 200
  batch_size: 1000
  advancing_C: 2
  log_freq: 10
  use_Z: false

config_4:
  config_name: "scGAN_CIR_signle_dt"
  process : 'CIR'
  S_0: 0.1
  kappa: 0.1
  S_bar: 0.1
  gamma : 0.1
  n_steps: 100
  n_paths: 1000
  dt: 0.05
  number_data_points: 100000
  epochs: 200
  batch_size: 1000
  advancing_C: 2
  log_freq: 10
  use_Z: true

config_5:
  config_name: "cGAN_GBM_multiple_dts"
  process : 'GBM'
  S_0: 0.1
  mu: 0.05
  sigma: 0.2
  n_steps: [40, 20, 10, 5, 4, 3, 2, 1]
  n_paths: 1000
  dt: [0.05, 0.1, 0.2, 0.4, 0.5, 0.67, 1, 2]
  number_data_points: 100000
  epochs: 200
  batch_size: 1000
  advancing_C: 2
  log_freq: 10
  use_Z: false